# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x05greet\"\x1f\n\x11UserDetailRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"J\n\x12UserDetailResponse\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t2V\n\rNotifications\x12\x45\n\x0eGetUserDetails\x12\x18.greet.UserDetailRequest\x1a\x19.greet.UserDetailResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERDETAILREQUEST']._serialized_start=21
  _globals['_USERDETAILREQUEST']._serialized_end=52
  _globals['_USERDETAILRESPONSE']._serialized_start=54
  _globals['_USERDETAILRESPONSE']._serialized_end=128
  _globals['_NOTIFICATIONS']._serialized_start=130
  _globals['_NOTIFICATIONS']._serialized_end=216
# @@protoc_insertion_point(module_scope)
