"""empty message

Revision ID: 12aa25db0708
Revises: 9940c9ec39f5
Create Date: 2023-12-05 11:14:26.801234

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
NUMBER_TYPE=[
    ("mobile", "Mobile Number"),
    ("mobile2", "Mobile2 Number"),
    ("home","Home Number"),
    ("office","Office Number")
    ]

# revision identifiers, used by Alembic.
revision = '12aa25db0708'
down_revision = '9940c9ec39f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sqlalchemy_utils.types.choice.ChoiceType(NUMBER_TYPE), nullable=True))
        batch_op.drop_constraint('phone_number_home_key', type_='unique')
        batch_op.drop_constraint('phone_number_mobile2_key', type_='unique')
        batch_op.drop_constraint('phone_number_office_key', type_='unique')
        batch_op.drop_column('home')
        batch_op.drop_column('office')
        batch_op.drop_column('mobile2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile2', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('office', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('home', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('phone_number_office_key', ['office'])
        batch_op.create_unique_constraint('phone_number_mobile2_key', ['mobile2'])
        batch_op.create_unique_constraint('phone_number_home_key', ['home'])
        batch_op.drop_column('type')

    # ### end Alembic commands ###
