"""empty message

Revision ID: 1f0489cc7d33
Revises: 0671784ab3f0
Create Date: 2023-11-30 13:59:25.132347

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "1f0489cc7d33"
down_revision = "0671784ab3f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("phone_number", schema=None) as batch_op:
        batch_op.alter_column(
            "mobile",
            existing_type=sa.VARCHAR(length=20),
            type_=sqlalchemy_utils.types.phone_number.PhoneNumberType(length=10),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "mobile2",
            existing_type=sa.VARCHAR(length=20),
            type_=sqlalchemy_utils.types.phone_number.PhoneNumberType(length=10),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "home",
            existing_type=sa.VARCHAR(length=20),
            type_=sqlalchemy_utils.types.phone_number.PhoneNumberType(length=10),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "office",
            existing_type=sa.VARCHAR(length=20),
            type_=sqlalchemy_utils.types.phone_number.PhoneNumberType(length=10),
            existing_nullable=True,
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("phone_number_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "phone_number", ["phone_number_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("phone_number_id")

    with op.batch_alter_table("phone_number", schema=None) as batch_op:
        batch_op.alter_column(
            "office",
            existing_type=sqlalchemy_utils.types.phone_number.PhoneNumberType(
                length=10
            ),
            type_=sa.VARCHAR(length=20),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "home",
            existing_type=sqlalchemy_utils.types.phone_number.PhoneNumberType(
                length=10
            ),
            type_=sa.VARCHAR(length=20),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "mobile2",
            existing_type=sqlalchemy_utils.types.phone_number.PhoneNumberType(
                length=10
            ),
            type_=sa.VARCHAR(length=20),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "mobile",
            existing_type=sqlalchemy_utils.types.phone_number.PhoneNumberType(
                length=10
            ),
            type_=sa.VARCHAR(length=20),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
