"""empty message

Revision ID: 3ec2eb0530e2
Revises: 2df8b23766f4
Create Date: 2023-11-29 20:01:40.478961

"""
from alembic import op
import sqlalchemy as sa
import models

# revision identifiers, used by Alembic.
revision = "3ec2eb0530e2"
down_revision = "2df8b23766f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("internal_id", models.ULIDType(length=26), nullable=True),
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column("first_name", sa.String(length=20), nullable=False),
        sa.Column("last_name", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password", sa.String(length=60), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by_id", sa.String(length=500), nullable=True),
        sa.Column("updated_by_id", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_created_by_id"), ["created_by_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_internal_id"), ["internal_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_user_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_updated_by_id"), ["updated_by_id"], unique=False
        )

    op.drop_table("base_model")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "base_model",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "username", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.Column(
            "password", sa.VARCHAR(length=60), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="base_model_pkey"),
        sa.UniqueConstraint("email", name="base_model_email_key"),
        sa.UniqueConstraint("username", name="base_model_username_key"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_updated_by_id"))
        batch_op.drop_index(batch_op.f("ix_user_is_active"))
        batch_op.drop_index(batch_op.f("ix_user_internal_id"))
        batch_op.drop_index(batch_op.f("ix_user_created_by_id"))

    op.drop_table("user")
    # ### end Alembic commands ###
