"""empty message

Revision ID: 5f57f8f97da7
Revises: 3ec2eb0530e2
Create Date: 2023-11-30 13:47:59.425190

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "5f57f8f97da7"
down_revision = "3ec2eb0530e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "phone_number",
        sa.Column(
            "mobile",
            sqlalchemy_utils.types.phone_number.PhoneNumberType(length=10),
            nullable=False,
        ),
        sa.Column(
            "mobile2",
            sqlalchemy_utils.types.phone_number.PhoneNumberType(length=10),
            nullable=True,
        ),
        sa.Column(
            "home",
            sqlalchemy_utils.types.phone_number.PhoneNumberType(length=10),
            nullable=True,
        ),
        sa.Column(
            "office",
            sqlalchemy_utils.types.phone_number.PhoneNumberType(length=10),
            nullable=True,
        ),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by_id", sa.String(length=500), nullable=True),
        sa.Column("updated_by_id", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("phone_number", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_phone_number_created_by_id"), ["created_by_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_phone_number_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_phone_number_updated_by_id"), ["updated_by_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("phone_number", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_phone_number_updated_by_id"))
        batch_op.drop_index(batch_op.f("ix_phone_number_is_active"))
        batch_op.drop_index(batch_op.f("ix_phone_number_created_by_id"))

    op.drop_table("phone_number")
    # ### end Alembic commands ###
