"""empty message

Revision ID: 9940c9ec39f5
Revises: fd5f74b3539e
Create Date: 2023-11-30 15:28:11.655178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9940c9ec39f5'
down_revision = 'fd5f74b3539e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_phone_number_id_fkey', type_='foreignkey')
        batch_op.drop_column('phone_number_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_phone_number_id_fkey', 'phone_number', ['phone_number_id'], ['id'])

    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
