"""empty message

Revision ID: b44160e9ba3f
Revises: 9940c9ec39f5
Create Date: 2023-12-05 09:51:51.708234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44160e9ba3f'
down_revision = '9940c9ec39f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('mobile', 'mobile2', 'home', 'office', name='numbertype')))
        batch_op.drop_constraint('phone_number_home_key', type_='unique')
        batch_op.drop_constraint('phone_number_mobile2_key', type_='unique')
        batch_op.drop_constraint('phone_number_office_key', type_='unique')
        batch_op.drop_column('office')
        batch_op.drop_column('mobile2')
        batch_op.drop_column('home')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mobile2', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('office', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('phone_number_office_key', ['office'])
        batch_op.create_unique_constraint('phone_number_mobile2_key', ['mobile2'])
        batch_op.create_unique_constraint('phone_number_home_key', ['home'])
        batch_op.drop_column('type')

    # ### end Alembic commands ###
