"""empty message

Revision ID: fd5f74b3539e
Revises: 6b80e8c581da
Create Date: 2023-11-30 15:21:18.195599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5f74b3539e'
down_revision = '6b80e8c581da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['home'])
        batch_op.create_unique_constraint(None, ['office'])
        batch_op.create_unique_constraint(None, ['mobile'])
        batch_op.create_unique_constraint(None, ['mobile2'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_number', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
